package bismaputra.bloodglucoselevelmonitor

import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.LinearLayoutManager
import bismaputra.bloodglucoselevelmonitor.databinding.FragmentGlucoseListBinding
import kotlinx.coroutines.launch

private const val TAG = "CrimeListFragment"

class GlucoseListFragment: Fragment() {
    private var _binding: FragmentGlucoseListBinding? = null
    private val binding
        get() = checkNotNull(_binding) {
            "Cannot access binding because it is null. Is the view visible?"
        }

    private val glucoseListViewModel: GlucoseListViewModel by viewModels()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _binding = FragmentGlucoseListBinding.inflate(inflater,container,false)
        //create a layout manager
        binding.glucoseRecyclerView.layoutManager = LinearLayoutManager(context)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        viewLifecycleOwner.lifecycleScope.launch {
            viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
                glucoseListViewModel.glucoses.collect { glucoses ->
                    binding.glucoseRecyclerView.adapter =
                        GlucoseListAdapter(glucoses){ glucoseDate ->
                            //GlucoseListFragmentDirections is a class automatically generated by safeargs
                            //here, we send the date to the second fragment
                            findNavController().navigate(GlucoseListFragmentDirections.showGlucoseDetail(glucoseDate))
                        }
                }
            }
        }
    }


    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}